# Test Case F: Exclude patterns test
version: "3.8"
services:
  service_f:
    image: alpine:latest
    command: ["sleep", "infinity"]
    volumes:
      - /home/jmagar/code/scripts/docker-backup/test-env/appdata/project-f:/data 